version: "3.8"

services:

  #-------------------------------#
  #----| Streams Kafka utils |----#
  #-------------------------------#
  producer:
    build: ./producer
    environment:
      KAFKA_URL: 'broker-1:9092,broker-2:29092'
    depends_on:
      - init-kafka
    ports:
      - 8992:8992

  data-provider:
    build: ./data-provider
    environment:
      PRODUCER_URL: producer
      PRODUCER_PORT: 8992
    depends_on:
      - producer

  consumer:
    build: ./consumer
    environment:
      KAFKA_URL: 'broker-1:9092,broker-2:29092'
    depends_on:
      - init-kafka
