# https://github.com/MathieuSoysal/Javadoc-publisher.yml
name: Deploy Javadoc

on:
  push:
    branches: [ master, release-*, develop, feature/javadoc]
  pull_request:
    branches: [ master, release-*, develop ]


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Javadoc
        description: 'Automatically  generate your Javadoc from your maven project and deploy it with GitHub Page on javadoc branch.'
        runs:
          using: "composite"
            steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - uses: actions/setup-java@v2
              with:
                java-version: 17
                distribution: 'adopt'
            - name: Generate Javadoc
              run: cd javadoc && mvn org.apache.maven.plugins:maven-javadoc-plugin:3.3.1:aggregate
              shell: bash
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.8
              with:
                BRANCH: gh-pages
                CLEAN: true
                FOLDER: javadoc/target/site/apidocs
                TARGET_FOLDER: javadoc