name: Deploy Javadoc

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc 🚀
        uses: AutoStreams/javadoc-ci-gen@1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVADOC_DIR: ./javadoc
          javadoc-branch: gh-pages
          java-version: 17